In [99]:
import pandas as pd
from sklearn import linear_model

In [85]:
%store -r dfmaster21

In [86]:
dfmaster21

,PLAYER NAME,AVERAGE_putting_scaled,AVERAGE_OTT_scaled,AVERAGE_ARTG_scaled,AVERAGE_ATG_scaled
0,Louis Oosthuizen,1.000000,0.527190,0.764983,0.743414
1,J.T. Poston,0.971358,0.463263,0.483502,0.401660
2,Ian Poulter,0.965926,0.484848,0.772391,0.519307
3,Patrick Reed,0.953086,0.516397,0.775084,0.678455
4,Zach Johnson,0.952099,0.428394,0.597980,0.608445
...,...,...,...,...,...
191,Kyle Stanley,0.271111,0.618929,0.504377,0.776254
192,Joseph Bramlett,0.265185,0.610627,0.639731,0.653555
193,Michael Gellerman,0.241975,0.522623,0.328620,0.721761
194,Byeong Hun An,0.194568,0.520963,0.731313,0.522916
195,Grayson Murray,0.000000,0.491490,0.175758,0.483941

In [87]:
wellsfargoleaderboard21 = pd.read_html("https://www.espn.com/golf/leaderboard?tournamentId=401243420")[0]

wellsfargoleaderboard21

,Unnamed: 0,POS,PLAYER,SCORE,R1,R2,R3,R4,TOT,EARNINGS,FEDEX PTS
0,NaN,1,Rory McIlroy,-10,72,66,68,68,274,"$1,458,000",500
1,NaN,2,Abraham Ancer,-9,69,70,70,66,275,"$882,900",300
2,NaN,T3,Viktor Hovland,-8,69,72,68,67,276,"$477,900",163
3,NaN,T3,Keith Mitchell,-8,67,71,66,72,276,"$477,900",163
4,NaN,5,Gary Woodland,-7,67,69,70,71,277,"$332,100",110
...,...,...,...,...,...,...,...,...,...,...,...
151,NaN,-,Justin Suh,CUT,71,84,--,--,155,--,0
152,NaN,-,Henrik Norlander,CUT,80,76,--,--,156,--,0
153,NaN,-,Cory Schneider,CUT,81,80,--,--,161,--,0
154,NaN,-,Danny Lee,WD,--,--,--,--,--,--,0
155,NaN,-,Seung-Yul Noh,WD,74,--,--,--,74,--,0

In [88]:
# Need to manually find the name of the first person cut on the leaderboard so we can remove all the people who were cut from the board. In this case it was harry higgs

wellsfargoleaderboard21 = wellsfargoleaderboard21[0:77]
wellsfargoleaderboard21 = wellsfargoleaderboard21[['PLAYER', 'TOT']]
wellsfargoleaderboard21.columns = ['PLAYER NAME', 'TOT']
# This final leaderboard is the dependant variable for our regression. In our regression we want the coefficients to be as negative as possible since we are trying to maximize the correlation between positive strokes gained but a lower score.
wellsfargoleaderboard21

        PLAYER NAME  TOT
0      Rory McIlroy  274
1     Abraham Ancer  275
2    Viktor Hovland  276
3    Keith Mitchell  276
4     Gary Woodland  277
..              ...  ...
72       Kevin Tway  293
73  Ted Potter, Jr.  293
74   Russell Henley  293
75      D.J. Trahan  296
76     Beau Hossler  298

[77 rows x 2 columns]

In [118]:
dfforregression = wellsfargoleaderboard21.merge(dfmaster21, on="PLAYER NAME", how="left")
df = dfforregression 
df = df.drop([54, 57, 60, 66])
df

,PLAYER NAME,TOT,AVERAGE_putting_scaled,AVERAGE_OTT_scaled,AVERAGE_ARTG_scaled,AVERAGE_ATG_scaled
0,Rory McIlroy,274,0.715062,0.791615,0.606734,0.723205
1,Abraham Ancer,275,0.826173,0.662931,0.514478,0.757849
2,Viktor Hovland,276,0.649383,0.789954,0.499663,0.811620
3,Keith Mitchell,276,0.594568,0.754255,0.296296,0.465897
4,Gary Woodland,277,0.585185,0.438771,0.575758,0.682786
5,Matt Wallace,279,0.678025,0.561644,0.671380,0.737640
6,Patrick Reed,279,0.953086,0.516397,0.775084,0.678455
7,Luke List,279,0.313580,0.748858,0.583165,0.668351
8,Bryson DeChambeau,280,0.847901,1.000000,0.470034,0.682786
9,Aaron Wise,280,0.409383,0.621005,0.688215,0.706604
10,Ben Martin,281,0.560494,0.574927,0.435690,0.581739
11,Scott Piercy,281,0.384691,0.555002,0.630303,0.579574
12,Satoshi Kodaira,281,0.631111,0.559568,0.314478,0.596536
13,Emiliano Grillo,282,0.571358,0.670403,0.277441,0.819199
14,Tommy Fleetwood,282,0.555062,0.462017,0.723906,0.596175
15,Charl Schwartzel,282,0.635062,0.506434,0.665320,0.643811
16,Xander Schauffele,282,0.859753,0.628061,0.585859,0.812342
17,C.T. Pan,283,0.569383,0.516812,0.620875,0.666185
18,Brian Harman,283,0.836049,0.572852,0.752189,0.548178
19,J.J. Spaun,283,0.426173,0.591532,0.483502,0.538434
20,Keegan Bradley,283,0.352099,0.653383,0.638384,0.886684
21,Joaquin Niemann,283,0.776790,0.748443,0.480135,0.695417
22,Joel Dahmen,283,0.452840,0.606476,0.495623,0.631180
23,Russell Knox,283,0.494321,0.525114,0.469360,0.766149
24,Bubba Watson,283,0.519012,0.772105,0.550842,0.614940
25,Nick Taylor,284,0.704198,0.523869,0.529966,0.499459
26,Pat Perez,284,0.806420,0.467829,0.631650,0.644533
27,J.T. Poston,284,0.971358,0.463263,0.483502,0.401660
28,Justin Thomas,284,0.635556,0.615193,0.726599,0.897871
29,Talor Gooch,284,0.691852,0.488169,0.645791,0.734753
30,Kevin Streelman,284,0.618765,0.599004,0.581145,0.728618
31,Brandon Hagy,284,0.544198,0.654628,0.614815,0.385420
32,Lanto Griffin,284,0.812346,0.525529,0.388552,0.719957
33,Vince Whaley,284,0.704691,0.587381,0.549495,0.430170
34,Cam Davis,284,0.708148,0.647156,0.411448,0.635150
35,Kyle Stanley,284,0.271111,0.618929,0.504377,0.776254
36,Brian Stuard,285,0.736296,0.456621,0.653872,0.593288
37,Patrick Rodgers,285,0.653333,0.644251,0.575758,0.433418
38,Stewart Cink,285,0.703704,0.491075,0.490909,0.728257
39,Sean O'Hair,285,0.491852,0.472395,0.573737,0.473114
40,Matt Jones,285,0.757531,0.569116,0.732660,0.425478
41,Richy Werenski,285,0.656296,0.428809,0.545455,0.511729
42,Wyndham Clark,286,0.600494,0.511416,0.722559,0.346806
43,Andrew Putnam,286,0.788148,0.302200,0.595960,0.617106
44,Corey Conners,286,0.618765,0.777086,0.410774,0.829664
45,Jhonattan Vegas,286,0.531852,0.786218,0.468687,0.670516
46,Peter Malnati,286,0.740247,0.402242,0.585859,0.538434
47,Harris English,286,0.891358,0.549191,0.688889,0.622880
48,Jason Dufner,286,0.429136,0.586135,0.548822,0.648863
49,Scott Stallings,286,0.637531,0.527605,0.336027,0.705161
50,Hank Lebioda,287,0.835556,0.462017,0.570370,0.697582
51,Zach Johnson,287,0.952099,0.428394,0.597980,0.608445
52,Kramer Hickok,287,0.496790,0.566210,0.684175,0.510285
53,Seamus Power,288,0.705679,0.522623,0.823569,0.719596
55,Sepp Straka,288,0.668148,0.547945,0.431650,0.618910
56,Hunter Mahan,288,0.865185,0.561229,0.000000,0.000000
58,Matthew NeSmith,289,0.436543,0.522623,0.471380,0.824251
59,Michael Gligic,289,0.812346,0.474471,0.324579,0.463371
61,K.H. Lee,289,0.506173,0.589041,0.663973,0.553952
62,Roger Sloan,289,0.593086,0.586550,0.551515,0.657885
63,Patton Kizzire,289,0.836049,0.483188,0.589226,0.638759
64,Shane Lowry,290,0.542716,0.564134,0.751515,0.773728
65,Bo Van Pelt,290,0.511605,0.444168,0.407407,0.540599
67,Carlos Ortiz,290,0.613333,0.619759,0.616162,0.591844
68,Phil Mickelson,291,0.606914,0.450809,0.455219,0.526525
69,K.J. Choi,292,0.372346,0.112080,0.606061,0.642006
70,Brendan Steele,292,0.558025,0.569946,0.538721,0.614940
71,Jimmy Walker,293,0.783210,0.243254,0.496970,0.453627
72,Kevin Tway,293,0.722963,0.459942,0.578451,0.486828
73,"Ted Potter, Jr.",293,0.378272,0.303030,0.465320,0.557200
74,Russell Henley,293,0.635062,0.547115,0.543434,0.877661
75,D.J. Trahan,296,0.344198,0.446658,0.430976,0.632624
76,Beau Hossler,298,0.724444,0.542134,0.534007,0.426200

In [120]:
# Define X and Y
x = df[['AVERAGE_putting_scaled', 'AVERAGE_OTT_scaled', 'AVERAGE_ARTG_scaled', 'AVERAGE_ATG_scaled']]
y = df['TOT']

In [121]:
regr = linear_model.LinearRegression()
regr.fit(x,y)

LinearRegression()

In [132]:
# Getting Each Coefficient
co = regr.coef_
Putting = co[0]
OTT = co[1]
ARTG = co[2]
ATG = co[3]

print(f'The Coefficient for putting is {Putting}')
print(f'The Coefficient for OTT is {OTT}')
print(f'The Coefficient for ARTG is {ARTG}')
print(f'The Coefficient for ATG is {ATG}')

sumofcoefficients = float(Putting) + float(OTT) + float(ARTG) + float(ATG)
print('The sum of coefficients is', sumofcoefficients)

The Coefficient for putting is -3.5830362507439357
The Coefficient for OTT is -17.547224363415797
The Coefficient for ARTG is -3.4318616302501774
The Coefficient for ATG is -3.98947009907508
The sum of coefficients is -28.55159234348499

In [137]:
# Find each contribution by putting the coefficient over the total
puttingcont = float(Putting)/sumofcoefficients
OTTcont = float(OTT)/sumofcoefficients
ARTGcont = float(ARTG)/sumofcoefficients
ATGcont = float(ATG)/sumofcoefficients

print(f'The putting contribution is {puttingcont}')
print(f'The OTT contribution is {OTTcont}')
print(f'The ARTG contribution is {ARTGcont}')
print(f'The ATG contribution is {ATGcont}')

The putting contribution is 0.12549339482151603
The OTT contribution is 0.6145795356110774
The ARTG contribution is 0.12019860710267084
The ATG contribution is 0.13972846246473578

In [138]:
%store puttingcont
%store OTTcont
%store ARTGcont
%store ATGcont

Stored 'puttingcont' (float)
Stored 'OTTcont' (float)
Stored 'ARTGcont' (float)
Stored 'ATGcont' (float)